import { View as NativeView, Text } from 'react-native'
export { Text } from 'react-native'

export * from './core/Stacks'
export * from './core/Sheets'
export * from './typo/DeferredFonts'
export * from './typo/SizableText'
export * from './typo/Heading'
export * from './OnboardingCarouselItem'
export * from './grid/ExampleGrid'
export * from './grid/Grid'
export * from './grid/GridTile'
export * from './grid/GridTileActionAdd'
export * from './grid/GridTileImage'
export * from './grid/GridTileList'
export * from './buttons/Button'
export * from './actions/NewRef'
export * from './atoms/ScreenWrapper'
export * from './atoms/Shareable'
export * from './atoms/DismissKeyboard'
export * from './inputs/Camera'
export * from './inputs/Picker'
export * from './inputs/SearchBar'
export * from './profiles/NewUserProfile'
export * from './profiles/Details'
export * from './profiles/Profile'
export * from './SwipeToGoBack'

export const Spinner = () => <Text>Loading</Text>
export const Paragraph = ({ children }: { children: React.ReactNode }) => <Text>{children}</Text>

